### ISSUE TITLE
Unicode Support?

### ISSUE THREAD

**Issue by frioux** [rbwinslow/hq#6]
It seems like the program assumes everything is ascii:

```
$ curl -s 'https://blog.afoolishmanifesto.com/' | hq //body
Traceback (most recent call last):
  File "/usr/bin/hq", line 9, in <module>
    load_entry_point('hq==0.0.4', 'console_scripts', 'hq')()
  File "/usr/lib/python2.7/site-packages/hq/hq.py", line 68, in main
    print(convert_results_to_output_text(result, pretty=(not args['--ugly']), preserve_space=preserve_space))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2651' in position 717: ordinal not in range(128)
```

**Comment by rbwinslow** [comment]
It started out that way, but I thought I had subsequently covered the bases for proper Unicode handling (there are a few tests). Obviously, I missed a spot. I'll check it out.
